### ISSUE TITLE
Request: make breakpoints configurable via ThemeProvider

### ISSUE THREAD

**Issue by angusfretwell** [jxnblk/hidden-styled#1]
Hello!

Thanks for making this; super handy! It would be nice if breakpoints were configurable, I guess via an array like `[40, 52, 64]` to keep it consistent with your other packages (e.g. `grid-styled`).

If it's something you'd accept a PR for, let me know and I'll put one together when I have a few moments :grin:

**Comment by jxnblk** [comment]
Yeah, this is a great idea – the one question in my mind is what the props should look like, since a configurable array would allow for any number of breakpoints. I'd happily look at a PR, but might try to tackle this as well

**Comment by angusfretwell** [comment]
Hmm. Thinking out loud... could do something like this:

```
const theme = {
  breakpoints: [40, 52, 64],
  breakpointNames: ['sm', 'md', 'lg'], 
}
```

`styled-system` and `grid-styled` don't define a 0/xs breakpoint so that would have to be hardcoded I guess.

**Comment by angusfretwell** [comment]
Alternatively could just use a different key in the theme with a key/value object:

```
const theme = {
  hiddenBreakpoints: {
    xs: 0,
    sm: 40, 
    ...
  }
}
```

**Comment by jxnblk** [comment]
Yeah, in the other styled-system-based libraries, I'm trying to move away from breakpoint naming conventions altogether with the array props. I think doing something like that with this component would look clunky with something like:

```jsx
<Hide hide={[ true, false, true ]} />
```

*or*

```jsx
<Hide x0 x1 />
```

But I'm wondering if there's something else that would be both easy to understand and also not require naming breakpoints...

**Comment by jxnblk** [comment]
> `breakpointNames: ['sm', 'md', 'lg']`

FWIW, I don't mind this as a step forward

**Comment by j** [comment]
Yeah, I wanted to use this with my own breakpoints and grid-styled, but doesn't work.  I cloned and added my breakpoints, but it hides it a few pixels too early.
