### ISSUE TITLE
Any idea on how to get this to work for server-side rendering?

### ISSUE THREAD

**Issue by westhechiang** [jxnblk/hidden-styled#4]
I implemented SSR and the server is rendering both components (ProgressiveBackground & Background):
```
        <ExtendedHide xs width="100%">
          <ProgressiveBackground
            content={bgImage}
            position="relative"
          >
            {children}
          </ProgressiveBackground>
        </ExtendedHide>
        <ExtendedHide lg md sm width="100%">
          <Background
            content={mobileImage}
            position="relative"
          >
            {children}
          </Background>
        </ExtendedHide>
```

ExtendedHide looks like this:
```
import styled from 'styled-components';
import Hide from 'hidden-styled';

const ExtendedHide = styled(Hide)`
  width: ${props => props.width || 'auto'};
`;

export default ExtendedHide;
```

**Comment by ckeeney** [comment]
This library hides elements using CSS:

https://github.com/jxnblk/hidden-styled/blob/9b5e2d6bab353c3f11e21f1207e0537cfe1364bd/src/Hide.js#L10-L14

Isn't it expected that both components get rendered into the DOM, and just that browsers or anything that handles CSS not render it to the screen?  I assume both elements are also rendered client-side.

**Comment by jxnblk** [comment]
Yes, CSS `display: none` only works in the browser, so I don't think there's any way to do what you describe with CSS
